{{- if .Values.adminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: central-admin-password
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  password: {{ .Values.adminPassword | quote }}
{{- end }}
