{{- range $env := .Values.environments }}
---
kind: Secret
apiVersion: v1
metadata:
  name: parasol-db
  namespace: {{ $env.namespace }}
stringData:
  database-user: {{ $.Values.database.user }}
  database-password: {{ $.Values.database.password }}
  database-name: {{ $.Values.database.name }}
type: Opaque
{{- end }}
