catalogSources:
  - name: redhat-operators-snapshot
    image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
    tag: v4.20_2026_02_11
    namespace: openshift-marketplace
    displayName: "Red Hat Operators (Snapshot)"
    publisher: "Red Hat Demo Platform"
    grpcPodConfig:
      extractContent:
        catalogDir: /configs
        cacheDir: /tmp/cache
