apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" "tekton-chains-config" "namespace" .Values.argocd.namespace "syncWave" "3") }}
spec:
  destination:
    namespace: openshift-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tekton-chains-config
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        vault:
          namespace: {{ .Values.vault.namespace }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=false
