{{- if .Values.tpa.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" (printf "%s-prerequisites" .Values.tpa.name) "namespace" .Values.argocd.namespace "syncWave" "2") }}
spec:
  destination:
    namespace: {{ .Values.tpa.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: trusted-profile-analyzer/charts/tpa-prerequisites
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        pgsql:
          user: {{ .Values.tpa.postgresql.user }}
          password: {{ .Values.tpa.postgresql.password | quote }}
          database: {{ .Values.tpa.postgresql.database }}
        oidc:
          issuerUrl: {{ .Values.tpa.oidcIssuer }}
          tpaCli:
            secret: {{ .Values.keycloak.client.tpaCli.secret | quote }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.tpa.name "namespace" .Values.argocd.namespace "syncWave" "3") }}
spec:
  destination:
    namespace: {{ .Values.tpa.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redhat-trusted-profile-analyzer
    repoURL: https://charts.openshift.io/
    targetRevision: "1.2.1"
    helm:
      valuesObject:
        appDomain: {{ .Values.tpa.appDomain }}
        openshift:
          enabled: true
          useServiceCa: true
        storage:
          type: s3
          accessKey:
            valueFrom:
              secretKeyRef:
                name: trustify
                key: AWS_ACCESS_KEY_ID
          secretKey:
            valueFrom:
              secretKeyRef:
                name: trustify
                key: AWS_SECRET_ACCESS_KEY
          bucket: trustify
          region: {{ .Values.tpa.s3.region }}
        database:
          host: tpa-postgresql
          name: {{ .Values.tpa.postgresql.database }}
          username: {{ .Values.tpa.postgresql.user }}
          password:
            valueFrom:
              secretKeyRef:
                name: tpa-postgresql
                key: database-password
          port: "5432"
          sslMode: disable
        oidc:
          issuerUrl: {{ .Values.tpa.oidcIssuer }}
          clients:
            frontend:
              clientId: tpa-frontend
            cli:
              clientId: tpa-cli
              clientSecret:
                valueFrom:
                  secretKeyRef:
                    name: oidc-tpa-cli
                    key: client-secret
        createDatabase: {}
        migrateDatabase: {}
        modules:
          createDatabase:
            enabled: true
          migrateDatabase:
            enabled: true
          createImporters:
            enabled: true
            importers:
              cve:
                cve:
                  period: 12h
                  source: https://github.com/CVEProject/cvelistV5
              osv-github:
                osv:
                  period: 12h
                  source: https://github.com/github/advisory-database
                  path: advisories/github-reviewed
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
