apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" "web-terminal" "namespace" .Values.argocd.namespace "syncWave" "1") }}
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: web-terminal
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
