---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: {{ .Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  auth:
    strategy: openshift
  deployment:
    cluster_wide_access: true
    accessible_namespaces:
      - "**"
    namespace: {{ .Values.istio.namespace }}
    pod_labels:
      sidecar.istio.io/inject: "false"
  external_services:
    grafana:
      enabled: false
    tracing:
      enabled: false
    prometheus:
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      auth:
        type: bearer
        use_kiali_token: true
  istio_namespace: {{ .Values.istio.namespace }}
