apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tpa-prerequisites.name" . }}-start
  labels:
    {{- include "tpa-prerequisites.labels" . | nindent 4 }}
  annotations:
    {{- include "tpa-prerequisites.argocd-syncwave" . | nindent 4 }}
data:
  extensions.sh: |
    psql -d $POSTGRESQL_DATABASE -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
