tpa-prerequisites:
  pgsql:
    user: trustify
    password: trustify
    database: trustify
  oidc:
    tpaCli:
      secret: ""

redhat-trusted-profile-analyzer:
  appDomain: ""
  storage:
    type: s3
    accessKey:
      valueFrom:
        secretKeyRef:
          name: trustify
          key: AWS_ACCESS_KEY_ID
    secretKey:
      valueFrom:
        secretKeyRef:
          name: trustify
          key: AWS_SECRET_ACCESS_KEY
    bucket: trustify
    region: ""
  database:
    host: tpa-postgresql
    name: trustify
    username: trustify
    password:
      valueFrom:
        secretKeyRef:
          name: tpa-postgresql
          key: database-password
    port: "5432"
    sslMode: disable
  oidc:
    issuerUrl: ""
    clients:
      frontend:
        clientId: tpa-frontend
      cli:
        clientId: tpa-cli
        clientSecret:
          valueFrom:
            secretKeyRef:
              name: oidc-tpa-cli
              key: client-secret
  createDatabase: {}
  migrateDatabase: {}
  modules:
    createDatabase:
      enabled: true
    migrateDatabase:
      enabled: true
    createImporters:
      enabled: true
      importers:
        cve:
          cve:
            period: 12h
            source: https://github.com/CVEProject/cvelistV5
        osv-github:
          osv:
            period: 12h
            source: https://github.com/github/advisory-database
            path: advisories/github-reviewed
